# Generated by Django 4.1.5 on 2023-01-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('conference', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Abbreviation of the committee', verbose_name='Abbreviation')),
                ('title', models.CharField(help_text='Title of the committee', max_length=100)),
                ('desc', models.TextField(help_text='Description of the committee')),
                ('chair', models.IntegerField(help_text='Id of the chair of the committee')),
                ('active', models.BooleanField(default=True)),
                ('guide', models.CharField(help_text='URL to the study guide for the committee', max_length=150)),
            ],
            options={
                'verbose_name': 'committee',
                'verbose_name_plural': 'committees',
            },
        ),
        migrations.CreateModel(
            name='CommitteeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.IntegerField(help_text='Id of the chair of the session')),
                ('committee',
                 models.ForeignKey(help_text='Committee of the session', on_delete=django.db.models.deletion.CASCADE,
                                   to='committee.committee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.session')),
            ],
            options={
                'verbose_name': 'committeesession',
                'verbose_name_plural': 'committeesessions',
            },
        ),
    ]
