# Generated by Django 4.1.5 on 2023-01-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('chair', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
