# Generated by Django 4.1.5 on 2023-01-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_committee_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'verbose_name': 'committee', 'verbose_name_plural': 'committees'},
        ),
        migrations.AddField(
            model_name='committee',
            name='guide',
            field=models.TextField(default=0, help_text='Study guide for the committee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='abv',
            field=models.CharField(help_text='Abbreviation of the committee', max_length=10),
        ),
        migrations.AlterField(
            model_name='committee',
            name='chair',
            field=models.PositiveSmallIntegerField(help_text='Chair of the committee'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='desc',
            field=models.TextField(help_text='Description of the committee'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='title',
            field=models.CharField(help_text='Title of the committee', max_length=100),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Number of the session')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committee')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the delegate')),
                ('email', models.EmailField(help_text='Email of the delegate', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.TextField(help_text='Country of the delegate')),
                ('active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committee')),
            ],
            options={
                'verbose_name': 'delegate',
                'verbose_name_plural': 'delegates',
            },
        ),
    ]
