# Generated by Django 4.1.5 on 2023-01-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_alter_committee_options_committee_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='guide',
            field=models.CharField(help_text='URL to the study guide for the committee', max_length=150),
        ),
    ]
