# Generated by Django 4.1.5 on 2023-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_committee_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegate',
        ),
    ]
