# Generated by Django 4.1.5 on 2023-01-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the chairperson', max_length=40)),
                ('email', models.EmailField(help_text='Email of the chairperson', max_length=254)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'chairperson',
                'verbose_name_plural': 'chairpeople',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Contact email of the delegation', max_length=254,
                                            verbose_name='Email')),
                ('active', models.BooleanField(default=True)),
                ('application_date', models.DateField(blank=True, help_text='Date of application', null=True,
                                                      verbose_name='Application date')),
                ('institution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
            options={
                'verbose_name': 'delegation',
                'verbose_name_plural': 'delegations',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delegate', max_length=40)),
                ('email', models.EmailField(help_text='Email of the delegate', max_length=254)),
                ('phone', models.CharField(help_text='Phone number of the delegate', max_length=40, null=True)),
                ('country', models.CharField(help_text='Country of the delegate', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('committee',
                 models.ForeignKey(help_text='Committee of the delegate', on_delete=django.db.models.deletion.CASCADE,
                                   to='committee.committee')),
                ('delegation', models.ForeignKey(help_text='Delegation of the delegate',
                                                 on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='participants.delegation')),
            ],
            options={
                'verbose_name': 'delegate',
                'verbose_name_plural': 'delegates',
            },
        ),
    ]
