# Generated by Django 4.1.5 on 2023-01-19 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='application_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date of application',
                                   null=True, verbose_name='Application date'),
        ),
    ]
