# Generated by Django 4.1.5 on 2023-01-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the institution', max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Slug of the institution', verbose_name='Slug')),
                ('email', models.EmailField(blank=True, help_text='Contact email of the institution', max_length=254,
                                            verbose_name='Email')),
                ('website', models.CharField(blank=True, help_text='Website of the institution', max_length=100,
                                             verbose_name='Website')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
            },
        ),
    ]
