name: Django CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DEBUG: ${{ vars.DEBUG }}
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ vars.DB_PASSWORD }}
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}
  EMAIL_HOST: ${{ vars.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}
  EMAIL_PORT: ${{ vars.EMAIL_PORT }}
  EMAIL_USE_TLS: ${{ vars.EMAIL_USE_TLS }}

jobs:
  build:
    name: Deploy to Production
    runs-on: self-hosted
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        environment: [Production]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Sync with DataBase
      run: |
        echo ${{ vars.DB_NAME }}
        python manage.py makemigrations
        python manage.py migrate
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
    - name: Run Tests
      run: |
        
